FROM maven:3.9.6-eclipse-temurin-17 AS build

# Set workdir
WORKDIR /app

# Copy pom.xml trước
COPY pom.xml .

# Download dependencies để cache layer
RUN mvn dependency:go-offline -B

# Copy toàn bộ source code
COPY src ./src

# Chạy Spring Boot (dev mode)
CMD ["mvn", "spring-boot:run"]
