# Dockerfile.dev
FROM maven:3.9-eclipse-temurin-17

WORKDIR /app

# chạy container với root hoặc UID/GID host
USER 1000:1000

# Mount source code từ host, target tạo trong container
VOLUME /app

# CMD Maven run với fork = false
CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.fork=false", "-Dspring-boot.run.profiles=docker"]
